### PR TITLE
[Component with its own class name as service type] LPS-197370 Refactor components from lima modules part 2

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:lima

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:lima

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:lima

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:startup

**Review by regiCesar21 — APPROVED** [review]
so esperar o resultado do relevant agora, pra saber se realmente tem algo relacionado com as mudancas

**Pull request closed without merging**
