### PR TITLE
[Component with its own class name as service type] LPS-199542 Refactor Helper components from document-library,  document-library-opener-google-drive-web, on-demand-admin, portal-workflow and user-associated-data-web

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:sf

**Review by regiCesar21 — APPROVED** [review]

**Comment by regiCesar21** [comment]
ci:test:relevant

**Pull request closed without merging**
