### PR TITLE
LPS-198392 WIP

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by michaelhashimoto** [comment]
I retriggered this build, I sent a fix for the issue that was seen on this pull:
https://github.com/brianchandotcom/liferay-portal/pull/143317

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by RenanUmV** [comment]
ci:stop

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by RenanUmV** [comment]
ci:test:echo

**Comment by RenanUmV** [comment]
ci:test:stop

**Comment by RenanUmV** [comment]
ci:stop

**Pull request closed without merging**
