### PR TITLE
LPS-171288 Remove "immediate = true" from Remaining modules

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by RenanUmV** [comment]
ci:test:startup

**Comment by RenanUmV** [comment]
ci:test:stable

**Comment by RenanUmV** [comment]
ci:test:help

**Comment by catarineaguiar** [comment]
ci:test:account

**Comment by catarineaguiar** [comment]
ci:test:clustering

**Comment by catarineaguiar** [comment]
ci:test:analytics-cloud-acceptance

**Comment by catarineaguiar** [comment]
@RenanUmV analisei os resultados e nao achei nenhuma regressao.

**Pull request closed without merging**
