### PR TITLE
[Component with its own class name as service type] LPS-198392 Refactor components from asset-publisher-web, batch-planner-rest-impl, portal-search-solr8-impl modules 

### PR DESCRIPTION
**Pull request by RenanUmV**

### CODE REVIEW

**Comment by RenanUmV** [comment]
ci:test:sf

**Comment by catarineaguiar** [comment]
ci:test:relevant

**Comment by catarineaguiar** [comment]
ci:test:echo

**Comment by catarineaguiar** [comment]
[AssetPublisherUseCase#ViewNotificationEmailWhenSetDynamicSubscriptionLimitToZero](https://testray.liferay.com/home/-/testray/case_results/2444713096?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2444710401%26testrayRunId%3D2444710466%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) falhou

Nao consta nenhuma mensagem no MockMock 
https://testray.liferay.com/reports/production/logs/2023-10/test-1-40/test-portal-acceptance-pullrequest(master)/6795/functional-tomcat90-mysql57-jdk8/16/10/LocalFile.AssetPublisherUseCase_ViewNotificationEmailWhenSetDynamicSubscriptionLimitToZero/screenshots/before0.jpg.gz?authuser=4

**Comment by RenanUmV** [comment]
Valeu Cat

**Pull request closed without merging**
